"""add is_active field for drawings

Revision ID: 30472ed8f3aa
Revises: 8fd285cbf7df
Create Date: 2022-11-21 08:52:08.494527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30472ed8f3aa'
down_revision = '8fd285cbf7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'is_active')
    # ### end Alembic commands ###