"""add concluded for drawings

Revision ID: 487a4f1638cb
Revises: 65f86d19deee
Create Date: 2022-11-22 07:05:34.701891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487a4f1638cb'
down_revision = '65f86d19deee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('has_concluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'has_concluded')
    # ### end Alembic commands ###