"""add more relationships

Revision ID: 5ecae21649f6
Revises: cd5b2e220811
Create Date: 2022-09-15 08:48:59.937009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecae21649f6'
down_revision = 'cd5b2e220811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###