"""add field for locking in winner

Revision ID: 810f500e7031
Revises: 30472ed8f3aa
Create Date: 2022-11-21 09:04:29.082014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810f500e7031'
down_revision = '30472ed8f3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawingprizes', sa.Column('confirmed_winner', sa.Integer(), nullable=True))
    op.add_column('drawingprizes', sa.Column('selected_entry', sa.Integer(), nullable=True))
    op.drop_constraint('drawingprizes_winner_fkey', 'drawingprizes', type_='foreignkey')
    op.create_foreign_key(None, 'drawingprizes', 'entries', ['confirmed_winner'], ['id'])
    op.create_foreign_key(None, 'drawingprizes', 'entries', ['selected_entry'], ['id'])
    op.drop_column('drawingprizes', 'winner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawingprizes', sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drawingprizes', type_='foreignkey')
    op.drop_constraint(None, 'drawingprizes', type_='foreignkey')
    op.create_foreign_key('drawingprizes_winner_fkey', 'drawingprizes', 'entries', ['winner'], ['id'])
    op.drop_column('drawingprizes', 'selected_entry')
    op.drop_column('drawingprizes', 'confirmed_winner')
    # ### end Alembic commands ###