"""add cascading deletion

Revision ID: 8fd285cbf7df
Revises: a9079d829436
Create Date: 2022-09-15 09:09:37.249917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd285cbf7df'
down_revision = 'a9079d829436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drawingprizes_drawing_id_fkey', 'drawingprizes', type_='foreignkey')
    op.drop_constraint('drawingprizes_winner_fkey', 'drawingprizes', type_='foreignkey')
    op.create_foreign_key(None, 'drawingprizes', 'drawings', ['drawing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'drawingprizes', 'entries', ['winner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drawingprizes', type_='foreignkey')
    op.drop_constraint(None, 'drawingprizes', type_='foreignkey')
    op.create_foreign_key('drawingprizes_winner_fkey', 'drawingprizes', 'entries', ['winner'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('drawingprizes_drawing_id_fkey', 'drawingprizes', 'drawings', ['drawing_id'], ['id'])
    # ### end Alembic commands ###