"""add field for if entry has won

Revision ID: b85e6aecbfdc
Revises: 810f500e7031
Create Date: 2022-11-21 09:22:21.065703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85e6aecbfdc'
down_revision = '810f500e7031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('has_won', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'has_won')
    # ### end Alembic commands ###