"""add bool for shipment

Revision ID: cd5b2e220811
Revises: 08df38113b1a
Create Date: 2022-09-15 04:35:41.024992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5b2e220811'
down_revision = '08df38113b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('ship_to_winner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prizes', 'ship_to_winner')
    # ### end Alembic commands ###